import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeContext from "@/context/themeContext";
import Heder from "@/pages/heder/heder";
import ProviderWrapper from "@/providers/ProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Heder />
        <ThemeContext>
          <ProviderWrapper>
            {children}
          </ProviderWrapper>
        </ThemeContext>
      </body>
    </html>
  );
}
